import type { Metadata, Viewport } from 'next'
import { cookies } from 'next/headers'
import { ThemeProvider, type Theme } from '@/lib/contexts/ThemeContext'
import { MotionProvider, type MotionPref } from '@/lib/contexts/MotionContext'
import ServiceWorkerRegister from '@/components/ServiceWorkerRegister'
import './globals.css'

export const metadata: Metadata = {
  title: 'GRIND',
  description: 'Track your gym progress',
  manifest: '/manifest.json',
  icons: {
    icon: [{ url: '/icon-192.png', sizes: '192x192', type: 'image/png' }],
    apple: [{ url: '/icon-192.png', sizes: '192x192', type: 'image/png' }],
  },
  appleWebApp: {
    capable: true,
    // Do NOT set statusBarStyle to 'black-translucent' — it triggers a confirmed
    // iOS 26+ WebKit bug where the viewport is offset upward by the status bar
    // height (~59px), leaving an equal dead gap at the bottom of the screen.
    // With 'default' (or omitted), iOS standalone mode uses display:standalone +
    // the manifest background_color to fill safe areas correctly.
    statusBarStyle: 'default',
    title: 'GRIND',
  },
}

// Resolve the initial theme from the cookie (default dark) so the SSR'd <html>
// class and the browser-chrome color match the user's saved preference — no flash.
async function getInitialTheme(): Promise<Theme> {
  const pref = (await cookies()).get('grind_theme_pref')?.value
  return pref === 'light' ? 'light' : 'dark'
}

// Same reasoning as theme: resolve server-side so the reduce-motion class is
// already on <html> for the first paint, no flash of un-reduced animation.
async function getInitialMotionPref(): Promise<MotionPref> {
  const pref = (await cookies()).get('grind_motion_pref')?.value
  return pref === 'reduce' ? 'reduce' : 'no-preference'
}

export async function generateViewport(): Promise<Viewport> {
  const theme = await getInitialTheme()
  return {
    width: 'device-width',
    initialScale: 1,
    // Allow pinch zoom for low-vision users (WCAG). Form controls stay ≥16px
    // so iOS will not auto-zoom on focus; bottom bars stay layout-safe without
    // locking scale.
    viewportFit: 'cover',
    themeColor: theme === 'light' ? '#ecebe7' : '#0f0f0f',
  }
}

// Physical pixel resolution + CSS point size/dpr for each splash image
// generated by scripts/generate-splash.mjs (portrait-only, matching the
// manifest's `orientation`). iOS Safari has no automatic splash mechanism —
// it only shows a branded launch screen if one of these exactly matches the
// device via the `media` query, otherwise it falls back to a blank flash.
const SPLASH_SCREENS = [
  { cssWidth: 430, cssHeight: 932, ratio: 3, name: '1290x2796' },
  { cssWidth: 393, cssHeight: 852, ratio: 3, name: '1179x2556' },
  { cssWidth: 390, cssHeight: 844, ratio: 3, name: '1170x2532' },
  { cssWidth: 428, cssHeight: 926, ratio: 3, name: '1284x2778' },
  { cssWidth: 375, cssHeight: 812, ratio: 3, name: '1125x2436' },
  { cssWidth: 414, cssHeight: 896, ratio: 3, name: '1242x2688' },
  { cssWidth: 414, cssHeight: 896, ratio: 2, name: '828x1792' },
  { cssWidth: 375, cssHeight: 667, ratio: 2, name: '750x1334' },
  { cssWidth: 320, cssHeight: 568, ratio: 2, name: '640x1136' },
]

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = await getInitialTheme()
  const motionPref = await getInitialMotionPref()
  const htmlClass = [theme === 'light' ? 'light' : null, motionPref === 'reduce' ? 'reduce-motion' : null]
    .filter(Boolean)
    .join(' ') || undefined

  return (
    <html lang="en" className={htmlClass}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Next.js appleWebApp.capable only emits the non-prefixed
            `mobile-web-app-capable` meta tag. The apple-prefixed version is
            still required on iOS for proper standalone mode behaviour. */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {SPLASH_SCREENS.map(s => (
          <link
            key={s.name}
            rel="apple-touch-startup-image"
            href={`/splash/${s.name}.png`}
            media={`(device-width: ${s.cssWidth}px) and (device-height: ${s.cssHeight}px) and (-webkit-device-pixel-ratio: ${s.ratio}) and (orientation: portrait)`}
          />
        ))}
      </head>
      <body>
        <ServiceWorkerRegister />
        <ThemeProvider initialTheme={theme}>
          <MotionProvider initialPref={motionPref}>{children}</MotionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
